### ISSUE TITLE
Should Atlas be cloned, forked, deployed, or other?

### ISSUE THREAD

**Issue by stoqe** [indigotree/atlas#48]
Hi Indigo Tree. 🤗

Firstly thanks for making Atlas available: it's seriously a god send and I'm super grateful to be able to use it to kickstart my Netlfiy Hugo builds. 

I'm no Github expert so I'm curious as to how I should use Atlas for my own purposes — should I be submoduling it (I don't even really know how to submodule but in the reading I've done before posting here mosts suggests I shouldn't be cloning or forking; I should be submoduling)?

I see and love the Deploy to Netlify button in the Atlas repo; that's obviously easy to do but is that what I should be doing where I want to use Atlas with my own custom theme? Again parts of Github confuse me so I might be missing something obvious to others, but if I deploy the Atlas repo to Netlify then change default files like config.toml (which I'd need to edit for my own site variables) then I can't integrate any future Atlas updates can I?

**Comment by crgeary** [comment]
Most common approach would be to clone it, and push it up to your own repo... And then optionally remove the `.git` folder to start your project commit history from scratch... The rough commands for this would be:

```
git clone git@github.com:indigotree/atlas.git
cd atlas
rm -rf .git
git init
git add .
git commit -m"Initial commit. Setup Atlas."
git remote add origin { YOUR NEW REPO }
git push origin master -u
```

Then you would go connect your repo to Netlify etc. This would essentially make you your own copy, and you wouldn't have any updates we make (more an that below).

* * *

If you use the "Deploy to Netlify" button, it does very similar, it essentially clones the project into your Github account, and connects it to Netlify at the same time. I don't think it removes the GIT commits like I mentioned above (haven't tested it). Then you can `git pull` your copy down to your computer to work on. Again, like the above you wouldn't have access to new updates we make (see below).

* * *

In regards to Atlas, and the updates we make etc.. Because this is a starting point for your current project, and not intended to be a framework that you can simply "update" to the latest version, we tend to not consider backwards compatibility of old Atlas features, and older versions of Hugo that you might be running on your projects.

I guess to summarise this, we don't offer any guarantee that a new version of Atlas has any backwards compatibility with the previous version(s). And our recommended solution is to clone it, or use the "button" (as they're essentially the same thing).

* * *

I hope that helps answer your question, by all means get back in touch if it didn't :)

**Comment by stoqe** [comment]
Thanks for the detailed reply. I guess I was also wondering how you handle updates for projects you've rolled out then?

**Comment by crgeary** [comment]
We roll these out manually. In some cases we don't roll them out at all, it depends if it makes sense for that project.
